### ISSUE TITLE
topic subscription problems

### ISSUE THREAD

**Issue by onlyjob** [stintel/vallumd#13]
In case I'm doing something wrong (or not doing what I should have) there must be a flaw in the documentation, otherwise bug because example does not work as described.

I've configured _mosquitto_ 1.5.9 on OpenWRT mostly with defaults (I've only modified the config to send logs to syslog).
I've created _ipset_ set (`ipset create blacklist4 hash:ip timeout 3600`) and started _vallumd_ 0.1.4 as follows:

~~~~
# vallumd -h 192.168.0.1 -t blacklist4
Thu Jan  9 20:47:26 2020 daemon.info vallumd[30411]: Connected to 192.168.0.1:1883
Thu Jan  9 20:47:26 2020 daemon.info vallumd[30411]: Subscribed to topic blacklist4
~~~~

Now I'm trying to communicate with _vallumd_ from my Debian 10 "buster" workstation (using mosquitto-clients 1.5.7):

~~~~
# mosquitto_pub -h 192.168.0.1 -t blacklist4/add -m 8.8.8.8  # nothing happens
~~~~

The following command added IP to the list successfully:

~~~~
# mosquitto_pub -h 192.168.0.1 -t blacklist4 -m 8.8.8.8
Thu Jan  9 20:50:53 2020 daemon.info vallumd[30411]: ipset: added 8.8.8.8 to blacklist4
~~~~

But I can not figure out how to delete an IP address from the list...

I suspect that something is wrong with how _vallumd_ subscribes to topics since `/*` messages are not coming through...

Please advise.

**Comment by stintel** [comment]
Removing IP addresses is not supported in vallumd 0.1.
