### ISSUE TITLE
SysVinit

### ISSUE THREAD

**Issue by szepeviktor** [stintel/vallumd#8]
I am planning to add sysvinit script as I think systemd is not stable.

**Comment by stintel** [comment]
If you do, please keep it as clean and small as possible, keep it compatible between distros still using sysvinit (avoid Debianism or Redhatisms), and make it work with the existing config file (don't add a new one).

**Comment by szepeviktor** [comment]
Maybe Redhat has no `/lib/init/init-d-script`
https://manpages.debian.org/stretch/sysvinit-utils/init-d-script.5.en.html

My first try is

```bash
#!/lib/init/init-d-script
### BEGIN INIT INFO
# Provides:          vallumd
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Centralize or distribute IPset blacklists
# Description:       This program allows you to centralize
#                    and distribute IP blacklists.
### END INIT INFO

# Author: Viktor Szépe <viktor@szepe.net>

DAEMON="/usr/sbin/vallumd"
DESC="Centralize or distribute IPset blacklists"

do_start_prepare() {
    START_ARGS="--background"
    DAEMON_ARGS="$VALLUMD_OPTIONS"
}
```

What do you think?

**Comment by stintel** [comment]
CentOS/RHEL 7 definitely doesn't have /lib/init/init-d-script. And I currently don't have a CentOS 6 host to check either. I'll be travelling as of tomorrow until November 6, I'll try to prepare a C6 host to test after.

**Comment by szepeviktor** [comment]
Try the world's [fastest](https://github.com/szepeviktor/wordpress-speedtest) cheap enterprise level provider https://www.upcloud.com/ , it takes 30 seconds.

**Comment by stintel** [comment]
Well if it's that easy, please try yourself if your script works on C6 or not. I am too busy with other stuff at the moment.

**Comment by szepeviktor** [comment]
No, it does not contain that helper script.

**Comment by koumdros** [comment]
if I got what you;re trying to do  correctly, the "service helper" scrip tin Centos 6 is 
/etc/init.d/functions

**Comment by szepeviktor** [comment]
@koumdros Thank you. init-d-script uses those functions.
init-d-script is a higher level of abstraction, see the above code how tiny it is.

**Comment by stintel** [comment]
Sorry, I am not going to accept a SysV init script that only works on a certain distribution (flavour). There are already 3 different init systems supported. Adding support for a 4th (SysV), that only supports Debian/Ubuntu opens the road for another SysV init script for RedHat/CentOS, and so on. This will get ugly fast. Such distro-specific init scripts belong in that specific distro package. You could ask your distribution to package vallumd and include the above init script.
